spring:
  data:
    mongodb:
      host: mongo-product-service
      port: 27017
#ESTA ES LA CONFIGURACION DEL ARCHIVO DE CONFIGURACION SOBREESCRIBE LA CONFIGURACION LOCAL DEFINICA EN EL MICROSERVICIO
server:
  port: 8006

#ESTA ES UNA CONFIGURACION PERSONALIZADA QUE SERA UTILIZADA DENTRO DEL COMPONENTE
configuracion:
  texto: configuracion entorno de qa de eureka config
